server:
  port: 7091
spring:
  application:
    name: msvc-student
  config:
    import: optional:configserver:http://localhost:8888


management:
  endpoints:
    web:
      exposure:
        include: "*"

